# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.1.2
_src_path: https://github.com/pybamm-team/pybamm-cookie.git
backend: hatch
branch: main
email: medha140904@gmail.com
full_name: medha-14
license: BSD-3-Clause
mypy: false
org: pybamm-team
platform: github
project_name: pybamm-reservoir-example
project_short_description: A battery modelling project to demonstrate the pybamm.Model()
    API for external models and parameter sets.
project_slug: pybamm_reservoir_example
url: https://github.com/pybamm-team/pybamm-reservoir-example
vcs: true
